<?php

use Illuminate\Database\Seeder;

class SubCategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_categories')->delete();
        $subCategories = [
            // レディースサブ
            ['id' => '1', 'category_id' => '1', 'subCategory_name' => 'トップス', 'subCategory_slug_name' => 'トップス', 'sort_no' => 1],
            ['id' => '2', 'category_id' => '1', 'subCategory_name' => 'ジャケット/アウター', 'subCategory_slug_name' => 'ジャケット/アウター', 'sort_no' => 2],
            ['id' => '3', 'category_id' => '1', 'subCategory_name' => 'パンツ', 'subCategory_slug_name' => 'パンツ', 'sort_no' => 3],
            ['id' => '4', 'category_id' => '1', 'subCategory_name' => 'スカート', 'subCategory_slug_name' => 'スカート', 'sort_no' => 4],
            ['id' => '5', 'category_id' => '1', 'subCategory_name' => 'ワンピース', 'subCategory_slug_name' => 'ワンピース', 'sort_no' => 5],
            ['id' => '6', 'category_id' => '1', 'subCategory_name' => '靴', 'subCategory_slug_name' => '靴', 'sort_no' => 6],
            ['id' => '7', 'category_id' => '1', 'subCategory_name' => 'ルームウェア/パジャマ', 'subCategory_slug_name' => 'ルームウェア/パジャマ', 'sort_no' => 7],
            ['id' => '8', 'category_id' => '1', 'subCategory_name' => 'レッグウェア', 'subCategory_slug_name' => 'レッグウェア', 'sort_no' => 8],
            ['id' => '9', 'category_id' => '1', 'subCategory_name' => '帽子', 'subCategory_slug_name' => '帽子', 'sort_no' => 9],
            ['id' => '10', 'category_id' => '1', 'subCategory_name' => 'バッグ', 'subCategory_slug_name' => 'バッグ', 'sort_no' => 10],
            ['id' => '11', 'category_id' => '1', 'subCategory_name' => 'アクセサリー', 'subCategory_slug_name' => 'アクセサリー', 'sort_no' => 11],
            ['id' => '12', 'category_id' => '1', 'subCategory_name' => 'ヘアアクセサリー', 'subCategory_slug_name' => 'ヘアアクセサリー', 'sort_no' => 12],
            ['id' => '13', 'category_id' => '1', 'subCategory_name' => '小物', 'subCategory_slug_name' => '小物', 'sort_no' => 13],
            ['id' => '14', 'category_id' => '1', 'subCategory_name' => '時計', 'subCategory_slug_name' => '時計', 'sort_no' => 14],
            ['id' => '15', 'category_id' => '1', 'subCategory_name' => 'ウィッグ/エクステ', 'subCategory_slug_name' => 'ウィッグ/エクステ', 'sort_no' => 15],
            ['id' => '16', 'category_id' => '1', 'subCategory_name' => '浴衣/水着', 'subCategory_slug_name' => '浴衣/水着', 'sort_no' => 16],
            ['id' => '17', 'category_id' => '1', 'subCategory_name' => 'スーツ/フォーマル/ドレス', 'subCategory_slug_name' => 'スーツ/フォーマル/ドレス', 'sort_no' => 17],
            ['id' => '18', 'category_id' => '1', 'subCategory_name' => 'マタニティ', 'subCategory_slug_name' => 'マタニティ', 'sort_no' => 18],
            ['id' => '19', 'category_id' => '1', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 19],
            // メンズサブ
            ['id' => '20', 'category_id' => '2', 'subCategory_name' => 'トップス', 'subCategory_slug_name' => 'トップス', 'sort_no' => 20],
            ['id' => '21', 'category_id' => '2', 'subCategory_name' => 'ジャケット/アウター', 'subCategory_slug_name' => 'ジャケット/アウター', 'sort_no' => 21],
            ['id' => '22', 'category_id' => '2', 'subCategory_name' => 'パンツ', 'subCategory_slug_name' => 'パンツ', 'sort_no' => 22],
            ['id' => '23', 'category_id' => '2', 'subCategory_name' => '靴', 'subCategory_slug_name' => '靴', 'sort_no' => 23],
            ['id' => '24', 'category_id' => '2', 'subCategory_name' => 'バッグ', 'subCategory_slug_name' => 'バッグ', 'sort_no' => 24],
            ['id' => '25', 'category_id' => '2', 'subCategory_name' => 'スーツ', 'subCategory_slug_name' => 'スーツ', 'sort_no' => 25],
            ['id' => '26', 'category_id' => '2', 'subCategory_name' => '帽子', 'subCategory_slug_name' => '帽子', 'sort_no' => 26],
            ['id' => '27', 'category_id' => '2', 'subCategory_name' => 'アクセサリー', 'subCategory_slug_name' => 'アクセサリー', 'sort_no' => 27],
            ['id' => '28', 'category_id' => '2', 'subCategory_name' => '小物', 'subCategory_slug_name' => '小物', 'sort_no' => 28],
            ['id' => '29', 'category_id' => '2', 'subCategory_name' => '時計', 'subCategory_slug_name' => '時計', 'sort_no' => 29],
            ['id' => '30', 'category_id' => '2', 'subCategory_name' => '水着', 'subCategory_slug_name' => '水着', 'sort_no' => 30],
            ['id' => '31', 'category_id' => '2', 'subCategory_name' => 'レッグウェア', 'subCategory_slug_name' => 'レッグウェア', 'sort_no' => 31],
            ['id' => '32', 'category_id' => '2', 'subCategory_name' => 'アンダーウェア', 'subCategory_slug_name' => 'アンダーウェア', 'sort_no' => 32],
            ['id' => '33', 'category_id' => '2', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 33],
            // // ベビー・キッズサブ
            // ['id' => '34', 'category_id' => '3', 'subCategory_name' => 'ベビー服(女の子用) ~95cm', 'subCategory_slug_name' => 'ベビー服(女の子用) ~95cm', 'sort_no' => 34],
            // ['id' => '35', 'category_id' => '3', 'subCategory_name' => 'ベビー服(男の子用) ~95cm', 'subCategory_slug_name' => 'ベビー服(男の子用) ~95cm', 'sort_no' => 35],
            // ['id' => '36', 'category_id' => '3', 'subCategory_name' => 'ベビー服(男女兼用) ~95cm', 'subCategory_slug_name' => 'ベビー服(男女兼用) ~95cm', 'sort_no' => 36],
            // ['id' => '37', 'category_id' => '3', 'subCategory_name' => 'キッズ服(女の子用) 100cm~', 'subCategory_slug_name' => 'キッズ服(女の子用) 100cm~', 'sort_no' => 37],
            // ['id' => '38', 'category_id' => '3', 'subCategory_name' => 'キッズ服(男の子用) 100cm~', 'subCategory_slug_name' => 'キッズ服(男の子用) 100cm~', 'sort_no' => 38],
            // ['id' => '39', 'category_id' => '3', 'subCategory_name' => 'キッズ服(男女兼用) 100cm~', 'subCategory_slug_name' => 'キッズ服(男女兼用) 100cm~', 'sort_no' => 39],
            // ['id' => '40', 'category_id' => '3', 'subCategory_name' => 'キッズ靴', 'subCategory_slug_name' => 'キッズ靴', 'sort_no' => 40],
            // ['id' => '41', 'category_id' => '3', 'subCategory_name' => '子ども用ファッション小物', 'subCategory_slug_name' => '子ども用ファッション小物', 'sort_no' => 41],
            // ['id' => '42', 'category_id' => '3', 'subCategory_name' => 'おむつ/トイレ/バス', 'subCategory_slug_name' => 'おむつ/トイレ/バス', 'sort_no' => 42],
            // ['id' => '43', 'category_id' => '3', 'subCategory_name' => '外出/移動用品', 'subCategory_slug_name' => '外出/移動用品', 'sort_no' => 43],
            // ['id' => '44', 'category_id' => '3', 'subCategory_name' => '授乳/食事', 'subCategory_slug_name' => '授乳/食事', 'sort_no' => 44],
            // ['id' => '45', 'category_id' => '3', 'subCategory_name' => 'ベビー家具/寝具/室内用品', 'subCategory_slug_name' => 'ベビー家具/寝具/室内用品', 'sort_no' => 45],
            // ['id' => '46', 'category_id' => '3', 'subCategory_name' => 'おもちゃ', 'subCategory_slug_name' => 'おもちゃ', 'sort_no' => 46],
            // ['id' => '47', 'category_id' => '3', 'subCategory_name' => '行事/記念品', 'subCategory_slug_name' => '行事/記念品', 'sort_no' => 47],
            // ['id' => '48', 'category_id' => '3', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 48],
            // // インテリア・住まい・小物サブ
            // ['id' => '49', 'category_id' => '4', 'subCategory_name' => 'キッチン/食器', 'subCategory_slug_name' => 'キッチン/食器', 'sort_no' => 49],
            // ['id' => '50', 'category_id' => '4', 'subCategory_name' => 'ベッド/マットレス', 'subCategory_slug_name' => 'ベッド/マットレス', 'sort_no' => 50],
            // ['id' => '51', 'category_id' => '4', 'subCategory_name' => 'ソファ/ソファベッド', 'subCategory_slug_name' => 'ソファ/ソファベッド', 'sort_no' => 51],
            // ['id' => '52', 'category_id' => '4', 'subCategory_name' => '椅子/チェア', 'subCategory_slug_name' => '椅子/チェア', 'sort_no' => 52],
            // ['id' => '53', 'category_id' => '4', 'subCategory_name' => '机/テーブル', 'subCategory_slug_name' => '机/テーブル', 'sort_no' => 53],
            // ['id' => '54', 'category_id' => '4', 'subCategory_name' => '収納家具', 'subCategory_slug_name' => '収納家具', 'sort_no' => 54],
            // ['id' => '55', 'category_id' => '4', 'subCategory_name' => 'ラグ/カーペット/マット', 'subCategory_slug_name' => 'ラグ/カーペット/マット', 'sort_no' => 55],
            // ['id' => '56', 'category_id' => '4', 'subCategory_name' => 'カーテン/ブラインド', 'subCategory_slug_name' => 'カーテン/ブラインド', 'sort_no' => 56],
            // ['id' => '57', 'category_id' => '4', 'subCategory_name' => 'ライト/照明', 'subCategory_slug_name' => 'ライト/照明', 'sort_no' => 57],
            // ['id' => '58', 'category_id' => '4', 'subCategory_name' => '寝具', 'subCategory_slug_name' => '寝具', 'sort_no' => 58],
            // ['id' => '59', 'category_id' => '4', 'subCategory_name' => 'インテリア小物', 'subCategory_slug_name' => 'インテリア小物', 'sort_no' => 59],
            // ['id' => '60', 'category_id' => '4', 'subCategory_name' => '季節/年中行事', 'subCategory_slug_name' => '季節/年中行事', 'sort_no' => 60],
            // ['id' => '61', 'category_id' => '4', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 61],
            // // 本・音楽・ゲーム サブ
            // ['id' => '62', 'category_id' => '5', 'subCategory_name' => '本', 'subCategory_slug_name' => '本', 'sort_no' => 62],
            // ['id' => '63', 'category_id' => '5', 'subCategory_name' => '漫画', 'subCategory_slug_name' => '漫画', 'sort_no' => 63],
            // ['id' => '64', 'category_id' => '5', 'subCategory_name' => '雑誌', 'subCategory_slug_name' => '雑誌', 'sort_no' => 64],
            // ['id' => '65', 'category_id' => '5', 'subCategory_name' => 'CD', 'subCategory_slug_name' => 'CD', 'sort_no' => 65],
            // ['id' => '66', 'category_id' => '5', 'subCategory_name' => 'DVD/ブルーレイ', 'subCategory_slug_name' => 'DVD/ブルーレイ', 'sort_no' => 66],
            // ['id' => '67', 'category_id' => '5', 'subCategory_name' => 'レコード', 'subCategory_slug_name' => 'レコード', 'sort_no' => 67],
            // ['id' => '68', 'category_id' => '5', 'subCategory_name' => 'テレビゲーム', 'subCategory_slug_name' => 'テレビゲーム', 'sort_no' => 68],
            // // おもちゃ・ホビー・グッズ サブ
            // ['id' => '69', 'category_id' => '6', 'subCategory_name' => 'おもちゃ', 'subCategory_slug_name' => 'おもちゃ', 'sort_no' => 69],
            // ['id' => '70', 'category_id' => '6', 'subCategory_name' => 'タレントグッズ', 'subCategory_slug_name' => 'タレントグッズ', 'sort_no' => 70],
            // ['id' => '71', 'category_id' => '6', 'subCategory_name' => 'コミック/アニメグッズ', 'subCategory_slug_name' => 'コミック/アニメグッズ', 'sort_no' => 71],
            // ['id' => '72', 'category_id' => '6', 'subCategory_name' => 'トレーディングカード', 'subCategory_slug_name' => 'トレーディングカード', 'sort_no' => 72],
            // ['id' => '73', 'category_id' => '6', 'subCategory_name' => 'フィギュア', 'subCategory_slug_name' => 'フィギュア', 'sort_no' => 73],
            // ['id' => '74', 'category_id' => '6', 'subCategory_name' => '楽器/器材', 'subCategory_slug_name' => '楽器/器材', 'sort_no' => 74],
            // ['id' => '75', 'category_id' => '6', 'subCategory_name' => 'コレクション', 'subCategory_slug_name' => 'コレクション', 'sort_no' => 75],
            // ['id' => '76', 'category_id' => '6', 'subCategory_name' => 'ミリタリー', 'subCategory_slug_name' => 'ミリタリー', 'sort_no' => 76],
            // ['id' => '77', 'category_id' => '6', 'subCategory_name' => '美術品', 'subCategory_slug_name' => '美術品', 'sort_no' => 77],
            // ['id' => '78', 'category_id' => '6', 'subCategory_name' => 'アート用品', 'subCategory_slug_name' => 'アート用品', 'sort_no' => 78],
            // ['id' => '79', 'category_id' => '6', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 79],
            // // コスメ・香水・美容 サブ
            // ['id' => '80', 'category_id' => '7', 'subCategory_name' => 'ベースメイク', 'subCategory_slug_name' => 'ベースメイク', 'sort_no' => 80],
            // ['id' => '81', 'category_id' => '7', 'subCategory_name' => 'メイクアップ', 'subCategory_slug_name' => 'メイクアップ', 'sort_no' => 81],
            // ['id' => '82', 'category_id' => '7', 'subCategory_name' => 'ネイルケア', 'subCategory_slug_name' => 'ネイルケア', 'sort_no' => 82],
            // ['id' => '83', 'category_id' => '7', 'subCategory_name' => '香水', 'subCategory_slug_name' => '香水', 'sort_no' => 83],
            // ['id' => '84', 'category_id' => '7', 'subCategory_name' => 'スキンケア/基礎化粧品', 'subCategory_slug_name' => 'スキンケア/基礎化粧品', 'sort_no' => 84],
            // ['id' => '85', 'category_id' => '7', 'subCategory_name' => 'ヘアケア', 'subCategory_slug_name' => 'ヘアケア', 'sort_no' => 85],
            // ['id' => '86', 'category_id' => '7', 'subCategory_name' => 'ボディケア', 'subCategory_slug_name' => 'ボディケア', 'sort_no' => 86],
            // ['id' => '87', 'category_id' => '7', 'subCategory_name' => 'オーラルケア', 'subCategory_slug_name' => 'オーラルケア', 'sort_no' => 87],
            // ['id' => '88', 'category_id' => '7', 'subCategory_name' => 'リラクゼーション', 'subCategory_slug_name' => 'リラクゼーション', 'sort_no' => 88],
            // ['id' => '89', 'category_id' => '7', 'subCategory_name' => 'ダイエット', 'subCategory_slug_name' => 'ダイエット', 'sort_no' => 89],
            // ['id' => '90', 'category_id' => '7', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 90],
            // // 家電・スマホ・カメラ
            // ['id' => '91', 'category_id' => '8', 'subCategory_name' => 'スマートフォン/携帯電話', 'subCategory_slug_name' => 'スマートフォン/携帯電話', 'sort_no' => 91],
            // ['id' => '92', 'category_id' => '8', 'subCategory_name' => 'スマホアクセサリー', 'subCategory_slug_name' => 'スマホアクセサリー', 'sort_no' => 92],
            // ['id' => '93', 'category_id' => '8', 'subCategory_name' => 'PC/タブレット', 'subCategory_slug_name' => 'PC/タブレット', 'sort_no' => 93],
            // ['id' => '94', 'category_id' => '8', 'subCategory_name' => 'カメラ', 'subCategory_slug_name' => 'カメラ', 'sort_no' => 94],
            // ['id' => '95', 'category_id' => '8', 'subCategory_name' => 'テレビ/映像機器', 'subCategory_slug_name' => 'テレビ/映像機器', 'sort_no' => 95],
            // ['id' => '96', 'category_id' => '8', 'subCategory_name' => 'オーディオ機器', 'subCategory_slug_name' => 'オーディオ機器', 'sort_no' => 96],
            // ['id' => '97', 'category_id' => '8', 'subCategory_name' => '美容/健康', 'subCategory_slug_name' => '美容/健康', 'sort_no' => 97],
            // ['id' => '98', 'category_id' => '8', 'subCategory_name' => '冷暖房/空調', 'subCategory_slug_name' => '冷暖房/空調', 'sort_no' => 98],
            // ['id' => '99', 'category_id' => '8', 'subCategory_name' => '生活家電', 'subCategory_slug_name' => '生活家電', 'sort_no' => 99],
            // ['id' => '100', 'category_id' => '8', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 100],
            // // スポーツ・レジャー
            // ['id' => '101', 'category_id' => '9', 'subCategory_name' => 'ゴルフ', 'subCategory_slug_name' => 'ゴルフ', 'sort_no' => 101],
            // ['id' => '102', 'category_id' => '9', 'subCategory_name' => 'フィッシング', 'subCategory_slug_name' => 'フィッシング', 'sort_no' => 102],
            // ['id' => '103', 'category_id' => '9', 'subCategory_name' => '自転車', 'subCategory_slug_name' => '自転車', 'sort_no' => 103],
            // ['id' => '104', 'category_id' => '9', 'subCategory_name' => 'トレーニング/エクササイズ', 'subCategory_slug_name' => 'トレーニング/エクササイズ', 'sort_no' => 104],
            // ['id' => '105', 'category_id' => '9', 'subCategory_name' => '野球', 'subCategory_slug_name' => '野球', 'sort_no' => 105],
            // ['id' => '106', 'category_id' => '9', 'subCategory_name' => 'サッカー/フットサル', 'subCategory_slug_name' => 'サッカー/フットサル', 'sort_no' => 106],
            // ['id' => '107', 'category_id' => '9', 'subCategory_name' => 'テニス', 'subCategory_slug_name' => 'テニス', 'sort_no' => 107],
            // ['id' => '108', 'category_id' => '9', 'subCategory_name' => 'スノーボード', 'subCategory_slug_name' => 'スノーボード', 'sort_no' => 108],
            // ['id' => '109', 'category_id' => '9', 'subCategory_name' => 'スキー', 'subCategory_slug_name' => 'スキー', 'sort_no' => 109],
            // ['id' => '110', 'category_id' => '9', 'subCategory_name' => 'その他スポーツ', 'subCategory_slug_name' => 'その他スポーツ', 'sort_no' => 110],
            // ['id' => '111', 'category_id' => '9', 'subCategory_name' => 'アウトドア', 'subCategory_slug_name' => 'アウトドア', 'sort_no' => 111],
            // ['id' => '112', 'category_id' => '9', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 112],
            // // ハンドメイド
            // ['id' => '113', 'category_id' => '10', 'subCategory_name' => 'アクセサリー(女性用)', 'subCategory_slug_name' => 'アクセサリー(女性用)', 'sort_no' => 113],
            // ['id' => '114', 'category_id' => '10', 'subCategory_name' => 'ファッション/小物', 'subCategory_slug_name' => 'ファッション/小物', 'sort_no' => 114],
            // ['id' => '115', 'category_id' => '10', 'subCategory_name' => 'アクセサリー/時計', 'subCategory_slug_name' => 'アクセサリー/時計', 'sort_no' => 115],
            // ['id' => '116', 'category_id' => '10', 'subCategory_name' => '日用品/インテリア', 'subCategory_slug_name' => '日用品/インテリア', 'sort_no' => 116],
            // ['id' => '117', 'category_id' => '10', 'subCategory_name' => '趣味/おもちゃ', 'subCategory_slug_name' => '趣味/おもちゃ', 'sort_no' => 117],
            // ['id' => '118', 'category_id' => '10', 'subCategory_name' => 'キッズ/ベビー', 'subCategory_slug_name' => 'キッズ/ベビー', 'sort_no' => 118],
            // ['id' => '119', 'category_id' => '10', 'subCategory_name' => '素材/材料', 'subCategory_slug_name' => '素材/材料', 'sort_no' => 119],
            // ['id' => '120', 'category_id' => '10', 'subCategory_name' => '二次創作物', 'subCategory_slug_name' => '二次創作物', 'sort_no' => 120],
            // ['id' => '121', 'category_id' => '10', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 121],
            // // チケット
            // ['id' => '122', 'category_id' => '11', 'subCategory_name' => '音楽', 'subCategory_slug_name' => '音楽', 'sort_no' => 122],
            // ['id' => '123', 'category_id' => '11', 'subCategory_name' => 'スポーツ', 'subCategory_slug_name' => 'スポーツ', 'sort_no' => 123],
            // ['id' => '124', 'category_id' => '11', 'subCategory_name' => '演劇/芸能', 'subCategory_slug_name' => '演劇/芸能', 'sort_no' => 124],
            // ['id' => '125', 'category_id' => '11', 'subCategory_name' => 'イベント', 'subCategory_slug_name' => 'イベント', 'sort_no' => 125],
            // ['id' => '126', 'category_id' => '11', 'subCategory_name' => '映画', 'subCategory_slug_name' => '映画', 'sort_no' => 126],
            // ['id' => '127', 'category_id' => '11', 'subCategory_name' => '施設利用券', 'subCategory_slug_name' => '施設利用券', 'sort_no' => 127],
            // ['id' => '128', 'category_id' => '11', 'subCategory_name' => '優待券/割引券', 'subCategory_slug_name' => '優待券/割引券', 'sort_no' => 128],
            // ['id' => '129', 'category_id' => '11', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 129],
            // // 自動車・オートバイ
            // ['id' => '130', 'category_id' => '12', 'subCategory_name' => '自動車本体', 'subCategory_slug_name' => '自動車本体', 'sort_no' => 130],
            // ['id' => '131', 'category_id' => '12', 'subCategory_name' => '自動車タイヤ/ホイール', 'subCategory_slug_name' => '自動車タイヤ/ホイール', 'sort_no' => 131],
            // ['id' => '132', 'category_id' => '12', 'subCategory_name' => '自動車パーツ', 'subCategory_slug_name' => '自動車パーツ', 'sort_no' => 132],
            // ['id' => '133', 'category_id' => '12', 'subCategory_name' => '自動車アクセサリー', 'subCategory_slug_name' => '自動車アクセサリー', 'sort_no' => 133],
            // ['id' => '134', 'category_id' => '12', 'subCategory_name' => 'オートバイ車体', 'subCategory_slug_name' => 'オートバイ車体', 'sort_no' => 134],
            // ['id' => '135', 'category_id' => '12', 'subCategory_name' => 'オートバイパーツ', 'subCategory_slug_name' => 'オートバイパーツ', 'sort_no' => 135],
            // ['id' => '136', 'category_id' => '12', 'subCategory_name' => 'オートバイアクセサリー', 'subCategory_slug_name' => 'オートバイアクセサリー', 'sort_no' => 136],
            // // その他
            // ['id' => '137', 'category_id' => '13', 'subCategory_name' => 'まとめ売り', 'subCategory_slug_name' => 'まとめ売り', 'sort_no' => 137],
            // ['id' => '138', 'category_id' => '13', 'subCategory_name' => 'ペット用品', 'subCategory_slug_name' => 'ペット用品', 'sort_no' => 138],
            // ['id' => '139', 'category_id' => '13', 'subCategory_name' => '食品', 'subCategory_slug_name' => '食品', 'sort_no' => 139],
            // ['id' => '140', 'category_id' => '13', 'subCategory_name' => '飲料/酒', 'subCategory_slug_name' => '飲料/酒', 'sort_no' => 140],
            // ['id' => '141', 'category_id' => '13', 'subCategory_name' => '日用品/生活雑貨/旅行', 'subCategory_slug_name' => '日用品/生活雑貨/旅行', 'sort_no' => 141],
            // ['id' => '142', 'category_id' => '13', 'subCategory_name' => 'アンティーク/コレクション', 'subCategory_slug_name' => 'アンティーク/コレクション', 'sort_no' => 142],
            // ['id' => '143', 'category_id' => '13', 'subCategory_name' => '文房具/事務用品', 'subCategory_slug_name' => '文房具/事務用品', 'sort_no' => 143],
            // ['id' => '144', 'category_id' => '13', 'subCategory_name' => '事務/店舗用品', 'subCategory_slug_name' => '事務/店舗用品', 'sort_no' => 144],
            // ['id' => '145', 'category_id' => '13', 'subCategory_name' => 'その他', 'subCategory_slug_name' => 'その他', 'sort_no' => 145],
        ];
        DB::table('sub_categories')->insert($subCategories);
    }
}
