<?php

use Illuminate\Database\Seeder;

class SuSubCategoiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_sub_categories')->delete();
        $subSubCategories = [
            // レディース/トップス
            ['id' => '1', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'Tシャツ/カットソー(半袖/袖なし)', 'subSubCategory_slug_name' => 'Tシャツ/カットソー(半袖/袖なし)', 'sort_no' => 1],
            ['id' => '2', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'Tシャツ/カットソー(七分/長袖)', 'subSubCategory_slug_name' => 'Tシャツ/カットソー(七分/長袖)', 'sort_no' => 2],
            ['id' => '3', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'シャツ/ブラウス(半袖/袖なし)', 'subSubCategory_slug_name' => 'シャツ/ブラウス(半袖/袖なし)', 'sort_no' => 3],
            ['id' => '4', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'シャツ/ブラウス(七分/長袖)', 'subSubCategory_slug_name' => 'シャツ/ブラウス(七分/長袖)', 'sort_no' => 4],
            ['id' => '5', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ポロシャツ', 'subSubCategory_slug_name' => 'ポロシャツ', 'sort_no' => 5],
            ['id' => '6', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'キャミソール', 'subSubCategory_slug_name' => 'キャミソール', 'sort_no' => 6],
            ['id' => '7', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'タンクトップ', 'subSubCategory_slug_name' => 'タンクトップ', 'sort_no' => 7],
            ['id' => '8', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ホルターネック', 'subSubCategory_slug_name' => 'ホルターネック', 'sort_no' => 8],
            ['id' => '9', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ニット/セーター', 'subSubCategory_slug_name' => 'ニット/セーター', 'sort_no' => 9],
            ['id' => '10', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'チュニック', 'subSubCategory_slug_name' => 'チュニック', 'sort_no' => 10],
            ['id' => '11', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'カーディガン/ボレロ', 'subSubCategory_slug_name' => 'カーディガン/ボレロ', 'sort_no' => 11],
            ['id' => '12', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'アンサンブル', 'subSubCategory_slug_name' => 'アンサンブル', 'sort_no' => 12],
            ['id' => '13', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ベスト/ジレ', 'subSubCategory_slug_name' => 'ベスト/ジレ', 'sort_no' => 13],
            ['id' => '14', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'パーカー', 'subSubCategory_slug_name' => 'パーカー', 'sort_no' => 14],
            ['id' => '15', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'トレーナー/スウェット', 'subSubCategory_slug_name' => 'トレーナー/スウェット', 'sort_no' => 15],
            ['id' => '16', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ベアトップ/チューブトップ', 'subSubCategory_slug_name' => 'ベアトップ/チューブトップ', 'sort_no' => 16],
            ['id' => '17', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'ジャージ', 'subSubCategory_slug_name' => 'ジャージ', 'sort_no' => 17],
            ['id' => '18', 'category_id' => '1', 'subCategory_id' => '1', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 18],
            // レディース/ジャケット/アウター
            ['id' => '19', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'テーラードジャケット', 'subSubCategory_slug_name' => 'テーラードジャケット', 'sort_no' => 19],
            ['id' => '20', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ノーカラージャケット', 'subSubCategory_slug_name' => 'ノーカラージャケット', 'sort_no' => 20],
            ['id' => '21', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'Gジャン/デニムジャケット', 'subSubCategory_slug_name' => 'Gジャン/デニムジャケット', 'sort_no' => 21],
            ['id' => '22', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'レザージャケット', 'subSubCategory_slug_name' => 'レザージャケット', 'sort_no' => 22],
            ['id' => '23', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ダウンジャケット', 'subSubCategory_slug_name' => 'ダウンジャケット', 'sort_no' => 23],
            ['id' => '24', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ライダースジャケット', 'subSubCategory_slug_name' => 'ライダースジャケット', 'sort_no' => 24],
            ['id' => '25', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ミリタリージャケット', 'subSubCategory_slug_name' => 'ミリタリージャケット', 'sort_no' => 25],
            ['id' => '26', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ダウンベスト', 'subSubCategory_slug_name' => 'ダウンベスト', 'sort_no' => 26],
            ['id' => '27', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ジャンパー/ブルゾン', 'subSubCategory_slug_name' => 'ジャンパー/ブルゾン', 'sort_no' => 27],
            ['id' => '28', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ポンチョ', 'subSubCategory_slug_name' => 'ポンチョ', 'sort_no' => 28],
            ['id' => '29', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ロングコート', 'subSubCategory_slug_name' => 'ロングコート', 'sort_no' => 29],
            ['id' => '30', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'トレンチコート', 'subSubCategory_slug_name' => 'トレンチコート', 'sort_no' => 30],
            ['id' => '31', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ダッフルコート', 'subSubCategory_slug_name' => 'ダッフルコート', 'sort_no' => 31],
            ['id' => '32', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'ピーコート', 'subSubCategory_slug_name' => 'ピーコート', 'sort_no' => 32],
            ['id' => '33', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'チェスターコート', 'subSubCategory_slug_name' => 'チェスターコート', 'sort_no' => 33],
            ['id' => '34', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'モッズコート', 'subSubCategory_slug_name' => 'モッズコート', 'sort_no' => 34],
            ['id' => '35', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'スタジャン', 'subSubCategory_slug_name' => 'スタジャン', 'sort_no' => 35],
            ['id' => '36', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => '毛皮/ファーコート', 'subSubCategory_slug_name' => '毛皮/ファーコート', 'sort_no' => 36],
            ['id' => '37', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'スプリングコート', 'subSubCategory_slug_name' => 'スプリングコート', 'sort_no' => 37],
            ['id' => '38', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'スカジャン', 'subSubCategory_slug_name' => 'スカジャン', 'sort_no' => 38],
            ['id' => '39', 'category_id' => '1', 'subCategory_id' => '2', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 39],
            // レディース/パンツ
            ['id' => '40', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'デニム/ジーンズ', 'subSubCategory_slug_name' => 'デニム/ジーンズ', 'sort_no' => 40],
            ['id' => '41', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'ショートパンツ', 'subSubCategory_slug_name' => 'ショートパンツ', 'sort_no' => 41],
            ['id' => '42', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'カジュアルパンツ', 'subSubCategory_slug_name' => 'カジュアルパンツ', 'sort_no' => 42],
            ['id' => '43', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'ハーフパンツ', 'subSubCategory_slug_name' => 'ハーフパンツ', 'sort_no' => 43],
            ['id' => '44', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'チノパン', 'subSubCategory_slug_name' => 'チノパン', 'sort_no' => 44],
            ['id' => '45', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'ワークパンツ/カーゴパンツ', 'subSubCategory_slug_name' => 'ワークパンツ/カーゴパンツ', 'sort_no' => 45],
            ['id' => '46', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'クロップドパンツ', 'subSubCategory_slug_name' => 'クロップドパンツ', 'sort_no' => 46],
            ['id' => '47', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'サロペット/オーバーオール', 'subSubCategory_slug_name' => 'サロペット/オーバーオール', 'sort_no' => 47],
            ['id' => '48', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'オールインワン', 'subSubCategory_slug_name' => 'オールインワン', 'sort_no' => 48],
            ['id' => '49', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'サルエルパンツ', 'subSubCategory_slug_name' => 'サルエルパンツ', 'sort_no' => 49],
            ['id' => '50', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'ガウチョパンツ', 'subSubCategory_slug_name' => 'ガウチョパンツ', 'sort_no' => 50],
            ['id' => '51', 'category_id' => '1', 'subCategory_id' => '3', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 51],
            // レディース/スカート
            ['id' => '52', 'category_id' => '1', 'subCategory_id' => '4', 'subSubCategory_name' => 'ミニスカート', 'subSubCategory_slug_name' => 'ミニスカート', 'sort_no' => 52],
            ['id' => '53', 'category_id' => '1', 'subCategory_id' => '4', 'subSubCategory_name' => 'ひざ丈スカート', 'subSubCategory_slug_name' => 'ひざ丈スカート', 'sort_no' => 53],
            ['id' => '54', 'category_id' => '1', 'subCategory_id' => '4', 'subSubCategory_name' => 'ロングスカート', 'subSubCategory_slug_name' => 'ロングスカート', 'sort_no' => 54],
            ['id' => '55', 'category_id' => '1', 'subCategory_id' => '4', 'subSubCategory_name' => 'キュロット', 'subSubCategory_slug_name' => 'キュロット', 'sort_no' => 55],
            ['id' => '56', 'category_id' => '1', 'subCategory_id' => '4', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 56],
            // レディース/ワンピース
            ['id' => '57', 'category_id' => '1', 'subCategory_id' => '5', 'subSubCategory_name' => 'ミニワンピース', 'subSubCategory_slug_name' => 'ミニワンピース', 'sort_no' => 57],
            ['id' => '58', 'category_id' => '1', 'subCategory_id' => '5', 'subSubCategory_name' => 'ひざ丈ワンピース', 'subSubCategory_slug_name' => 'ひざ丈ワンピース', 'sort_no' => 58],
            ['id' => '59', 'category_id' => '1', 'subCategory_id' => '5', 'subSubCategory_name' => 'ロングワンピース', 'subSubCategory_slug_name' => 'ロングワンピース', 'sort_no' => 59],
            ['id' => '60', 'category_id' => '1', 'subCategory_id' => '5', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 60],
            // レディース/靴
            ['id' => '61', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'ハイヒール/パンプス', 'subSubCategory_slug_name' => 'ハイヒール/パンプス', 'sort_no' => 61],
            ['id' => '62', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'ブーツ', 'subSubCategory_slug_name' => 'ブーツ', 'sort_no' => 62],
            ['id' => '63', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'サンダル', 'subSubCategory_slug_name' => 'サンダル', 'sort_no' => 63],
            ['id' => '64', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'スニーカー', 'subSubCategory_slug_name' => 'スニーカー', 'sort_no' => 64],
            ['id' => '65', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'ミュール', 'subSubCategory_slug_name' => 'ミュール', 'sort_no' => 65],
            ['id' => '66', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'モカシン', 'subSubCategory_slug_name' => 'モカシン', 'sort_no' => 66],
            ['id' => '67', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'ローファー/革靴', 'subSubCategory_slug_name' => 'ローファー/革靴', 'sort_no' => 67],
            ['id' => '68', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'フラットシューズ/バレエシューズ', 'subSubCategory_slug_name' => 'フラットシューズ/バレエシューズ', 'sort_no' => 68],
            ['id' => '69', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => '長靴/レインシューズ', 'subSubCategory_slug_name' => '長靴/レインシューズ', 'sort_no' => 69],
            ['id' => '70', 'category_id' => '1', 'subCategory_id' => '6', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 70],
            // レディース/ルームウェア/パジャマ
            ['id' => '71', 'category_id' => '1', 'subCategory_id' => '7', 'subSubCategory_name' => 'パジャマ', 'subSubCategory_slug_name' => 'パジャマ', 'sort_no' => 71],
            ['id' => '72', 'category_id' => '1', 'subCategory_id' => '7', 'subSubCategory_name' => 'ルームウェア', 'subSubCategory_slug_name' => 'ルームウェア', 'sort_no' => 72],
            // レディース/レッグウェア
            ['id' => '73', 'category_id' => '1', 'subCategory_id' => '8', 'subSubCategory_name' => 'ソックス', 'subSubCategory_slug_name' => 'ソックス', 'sort_no' => 73],
            ['id' => '74', 'category_id' => '1', 'subCategory_id' => '8', 'subSubCategory_name' => 'スパッツ/レギンス', 'subSubCategory_slug_name' => 'スパッツ/レギンス', 'sort_no' => 74],
            ['id' => '75', 'category_id' => '1', 'subCategory_id' => '8', 'subSubCategory_name' => 'ストッキング/タイツ', 'subSubCategory_slug_name' => 'ストッキング/タイツ', 'sort_no' => 75],
            ['id' => '76', 'category_id' => '1', 'subCategory_id' => '8', 'subSubCategory_name' => 'レッグウォーマー', 'subSubCategory_slug_name' => 'レッグウォーマー', 'sort_no' => 76],
            ['id' => '77', 'category_id' => '1', 'subCategory_id' => '8', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 77],
            // レディース/帽子
            ['id' => '78', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'ニットキャップ/ビーニー', 'subSubCategory_slug_name' => 'ニットキャップ/ビーニー', 'sort_no' => 78],
            ['id' => '79', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'ハット', 'subSubCategory_slug_name' => 'ハット', 'sort_no' => 79],
            ['id' => '80', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'ハンチング/ベレー帽', 'subSubCategory_slug_name' => 'ハンチング/ベレー帽', 'sort_no' => 80],
            ['id' => '81', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'キャップ', 'subSubCategory_slug_name' => 'キャップ', 'sort_no' => 81],
            ['id' => '82', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'キャスケット', 'subSubCategory_slug_name' => 'キャスケット', 'sort_no' => 82],
            ['id' => '83', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => '麦わら帽子', 'subSubCategory_slug_name' => '麦わら帽子', 'sort_no' => 83],
            ['id' => '84', 'category_id' => '1', 'subCategory_id' => '9', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 84],
            // レディース/バッグ
            ['id' => '85', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ハンドバッグ', 'subSubCategory_slug_name' => 'ハンドバッグ', 'sort_no' => 85],
            ['id' => '86', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'トートバッグ', 'subSubCategory_slug_name' => 'トートバッグ', 'sort_no' => 86],
            ['id' => '87', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'エコバッグ', 'subSubCategory_slug_name' => 'エコバッグ', 'sort_no' => 87],
            ['id' => '88', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'リュック/バックパック', 'subSubCategory_slug_name' => 'リュック/バックパック', 'sort_no' => 88],
            ['id' => '89', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ボストンバッグ', 'subSubCategory_slug_name' => 'ボストンバッグ', 'sort_no' => 89],
            ['id' => '90', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'スポーツバッグ', 'subSubCategory_slug_name' => 'スポーツバッグ', 'sort_no' => 90],
            ['id' => '91', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ショルダーバッグ', 'subSubCategory_slug_name' => 'ショルダーバッグ', 'sort_no' => 91],
            ['id' => '92', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'クラッチバッグ', 'subSubCategory_slug_name' => 'クラッチバッグ', 'sort_no' => 92],
            ['id' => '93', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ポーチ/バニティ', 'subSubCategory_slug_name' => 'ポーチ/バニティ', 'sort_no' => 93],
            ['id' => '94', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ボディバッグ/ウェストバッグ', 'subSubCategory_slug_name' => 'ボディバッグ/ウェストバッグ', 'sort_no' => 94],
            ['id' => '95', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'マザーズバッグ', 'subSubCategory_slug_name' => 'マザーズバッグ', 'sort_no' => 95],
            ['id' => '96', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'メッセンジャーバッグ', 'subSubCategory_slug_name' => 'メッセンジャーバッグ', 'sort_no' => 96],
            ['id' => '97', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ビジネスバッグ', 'subSubCategory_slug_name' => 'ビジネスバッグ', 'sort_no' => 97],
            ['id' => '98', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => '旅行用バッグ/キャリーバッグ', 'subSubCategory_slug_name' => '旅行用バッグ/キャリーバッグ', 'sort_no' => 98],
            ['id' => '99', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'ショップ袋', 'subSubCategory_slug_name' => 'ショップ袋', 'sort_no' => 99],
            ['id' => '100', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => '和装用バッグ', 'subSubCategory_slug_name' => '和装用バッグ', 'sort_no' => 100],
            ['id' => '101', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'かごバッグ', 'subSubCategory_slug_name' => 'かごバッグ', 'sort_no' => 101],
            ['id' => '102', 'category_id' => '1', 'subCategory_id' => '10', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 102],
            // レディース/アクセサリー
            ['id' => '103', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'ネックレス', 'subSubCategory_slug_name' => 'ネックレス', 'sort_no' => 103],
            ['id' => '104', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'ブレスレット', 'subSubCategory_slug_name' => 'ブレスレット', 'sort_no' => 104],
            ['id' => '105', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'バングル/リストバンド', 'subSubCategory_slug_name' => 'バングル/リストバンド', 'sort_no' => 105],
            ['id' => '106', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'リング', 'subSubCategory_slug_name' => 'リング', 'sort_no' => 106],
            ['id' => '107', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'ピアス(片耳用)', 'subSubCategory_slug_name' => 'ピアス(片耳用)', 'sort_no' => 107],
            ['id' => '108', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'ピアス(両耳用)', 'subSubCategory_slug_name' => 'ピアス(両耳用)', 'sort_no' => 108],
            ['id' => '109', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'イヤリング', 'subSubCategory_slug_name' => 'イヤリング', 'sort_no' => 109],
            ['id' => '110', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'アンクレット', 'subSubCategory_slug_name' => 'アンクレット', 'sort_no' => 110],
            ['id' => '111', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'ブローチ/コサージュ', 'subSubCategory_slug_name' => 'ブローチ/コサージュ', 'sort_no' => 111],
            ['id' => '112', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'チャーム', 'subSubCategory_slug_name' => 'チャーム', 'sort_no' => 112],
            ['id' => '113', 'category_id' => '1', 'subCategory_id' => '11', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 113],
            // レディース/ヘアアクセサリー
            ['id' => '114', 'category_id' => '1', 'subCategory_id' => '12', 'subSubCategory_name' => 'ヘアゴム/シュシュ', 'subSubCategory_slug_name' => 'ヘアゴム/シュシュ', 'sort_no' => 114],
            ['id' => '115', 'category_id' => '1', 'subCategory_id' => '12', 'subSubCategory_name' => 'ヘアバンド/カチューシャ', 'subSubCategory_slug_name' => 'ヘアバンド/カチューシャ', 'sort_no' => 115],
            ['id' => '116', 'category_id' => '1', 'subCategory_id' => '12', 'subSubCategory_name' => 'ヘアピン', 'subSubCategory_slug_name' => 'ヘアピン', 'sort_no' => 116],
            ['id' => '117', 'category_id' => '1', 'subCategory_id' => '12', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 117],
            // レディース/小物
            ['id' => '118', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '長財布', 'subSubCategory_slug_name' => '長財布', 'sort_no' => 118],
            ['id' => '119', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '折り財布', 'subSubCategory_slug_name' => '折り財布', 'sort_no' => 119],
            ['id' => '120', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'コインケース/小銭入れ', 'subSubCategory_slug_name' => 'コインケース/小銭入れ', 'sort_no' => 120],
            ['id' => '121', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '名刺入れ/定期入れ', 'subSubCategory_slug_name' => '名刺入れ/定期入れ', 'sort_no' => 121],
            ['id' => '122', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'キーケース', 'subSubCategory_slug_name' => 'キーケース', 'sort_no' => 122],
            ['id' => '123', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'キーホルダー', 'subSubCategory_slug_name' => 'キーホルダー', 'sort_no' => 123],
            ['id' => '124', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '手袋/アームカバー', 'subSubCategory_slug_name' => '手袋/アームカバー', 'sort_no' => 124],
            ['id' => '125', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'ハンカチ', 'subSubCategory_slug_name' => 'ハンカチ', 'sort_no' => 125],
            ['id' => '126', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'ベルト', 'subSubCategory_slug_name' => 'ベルト', 'sort_no' => 126],
            ['id' => '127', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'ストール/スヌード', 'subSubCategory_slug_name' => 'ストール/スヌード', 'sort_no' => 127],
            ['id' => '128', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'バンダナ/スカーフ', 'subSubCategory_slug_name' => 'バンダナ/スカーフ', 'sort_no' => 128],
            ['id' => '129', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'ネックウォーマー', 'subSubCategory_slug_name' => 'ネックウォーマー', 'sort_no' => 129],
            ['id' => '130', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'サスペンダー', 'subSubCategory_slug_name' => 'サスペンダー', 'sort_no' => 130],
            ['id' => '131', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'サングラス/メガネ', 'subSubCategory_slug_name' => 'サングラス/メガネ', 'sort_no' => 131],
            ['id' => '132', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'モバイルケース/カバー', 'subSubCategory_slug_name' => 'モバイルケース/カバー', 'sort_no' => 132],
            ['id' => '133', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '手帳', 'subSubCategory_slug_name' => '手帳', 'sort_no' => 133],
            ['id' => '134', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'イヤマフラー', 'subSubCategory_slug_name' => 'イヤマフラー', 'sort_no' => 134],
            ['id' => '135', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => '傘', 'subSubCategory_slug_name' => '傘', 'sort_no' => 135],
            ['id' => '136', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'レインコート/ポンチョ', 'subSubCategory_slug_name' => 'レインコート/ポンチョ', 'sort_no' => 136],
            ['id' => '137', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'ミラー', 'subSubCategory_slug_name' => 'ミラー', 'sort_no' => 137],
            ['id' => '138', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'タバコグッズ', 'subSubCategory_slug_name' => 'タバコグッズ', 'sort_no' => 138],
            ['id' => '139', 'category_id' => '1', 'subCategory_id' => '13', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 139],
            // レディース/時計
            ['id' => '140', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => '腕時計(アナログ)', 'subSubCategory_slug_name' => '腕時計(アナログ)', 'sort_no' => 140],
            ['id' => '141', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => '腕時計(デジタル)', 'subSubCategory_slug_name' => '腕時計(デジタル)', 'sort_no' => 141],
            ['id' => '142', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => 'ラバーベルト', 'subSubCategory_slug_name' => 'ラバーベルト', 'sort_no' => 142],
            ['id' => '143', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => 'レザーベルト', 'subSubCategory_slug_name' => 'レザーベルト', 'sort_no' => 143],
            ['id' => '144', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => '金属ベルト', 'subSubCategory_slug_name' => '金属ベルト', 'sort_no' => 144],
            ['id' => '145', 'category_id' => '1', 'subCategory_id' => '14', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 145],
            // レディース/ウィッグ/エクステ
            ['id' => '146', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => '前髪ウィッグ', 'subSubCategory_slug_name' => '前髪ウィッグ', 'sort_no' => 146],
            ['id' => '147', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => 'ロングストレート', 'subSubCategory_slug_name' => 'ロングストレート', 'sort_no' => 147],
            ['id' => '148', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => 'ロングカール', 'subSubCategory_slug_name' => 'ロングカール', 'sort_no' => 148],
            ['id' => '149', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => 'ショートストレート', 'subSubCategory_slug_name' => 'ショートストレート', 'sort_no' => 149],
            ['id' => '150', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => 'ショートカール', 'subSubCategory_slug_name' => 'ショートカール', 'sort_no' => 150],
            ['id' => '151', 'category_id' => '1', 'subCategory_id' => '15', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 151],
            // レディース/浴衣/水着
            ['id' => '152', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '浴衣', 'subSubCategory_slug_name' => '浴衣', 'sort_no' => 152],
            ['id' => '153', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '着物', 'subSubCategory_slug_name' => '着物', 'sort_no' => 153],
            ['id' => '154', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '振袖', 'subSubCategory_slug_name' => '振袖', 'sort_no' => 154],
            ['id' => '155', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '長襦袢/半襦袢', 'subSubCategory_slug_name' => '長襦袢/半襦袢', 'sort_no' => 155],
            ['id' => '156', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '水着セパレート', 'subSubCategory_slug_name' => '水着セパレート', 'sort_no' => 156],
            ['id' => '157', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '水着ワンピース', 'subSubCategory_slug_name' => '水着ワンピース', 'sort_no' => 157],
            ['id' => '158', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => '水着スポーツ用', 'subSubCategory_slug_name' => '水着スポーツ用', 'sort_no' => 158],
            ['id' => '159', 'category_id' => '1', 'subCategory_id' => '16', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 159],
            // レディース/スーツ/フォーマル/ドレス
            ['id' => '160', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'スカートスーツ上下', 'subSubCategory_slug_name' => 'スカートスーツ上下', 'sort_no' => 160],
            ['id' => '161', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'パンツスーツ上下', 'subSubCategory_slug_name' => 'パンツスーツ上下', 'sort_no' => 161],
            ['id' => '162', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'ドレス', 'subSubCategory_slug_name' => 'ドレス', 'sort_no' => 162],
            ['id' => '163', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'パーティーバッグ', 'subSubCategory_slug_name' => 'パーティーバッグ', 'sort_no' => 163],
            ['id' => '164', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'シューズ', 'subSubCategory_slug_name' => 'シューズ', 'sort_no' => 164],
            ['id' => '165', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'ウェディング', 'subSubCategory_slug_name' => 'ウェディング', 'sort_no' => 165],
            ['id' => '166', 'category_id' => '1', 'subCategory_id' => '17', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 166],
            // レディース/マタニティ
            ['id' => '167', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'トップス', 'subSubCategory_slug_name' => 'トップス', 'sort_no' => 167],
            ['id' => '168', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'アウター', 'subSubCategory_slug_name' => 'アウター', 'sort_no' => 168],
            ['id' => '169', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'インナー', 'subSubCategory_slug_name' => 'インナー', 'sort_no' => 169],
            ['id' => '170', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'ワンピース', 'subSubCategory_slug_name' => 'ワンピース', 'sort_no' => 170],
            ['id' => '171', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'パンツ/スパッツ', 'subSubCategory_slug_name' => 'パンツ/スパッツ', 'sort_no' => 171],
            ['id' => '172', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'スカート', 'subSubCategory_slug_name' => 'スカート', 'sort_no' => 172],
            ['id' => '173', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'パジャマ', 'subSubCategory_slug_name' => 'パジャマ', 'sort_no' => 173],
            ['id' => '174', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => '授乳服', 'subSubCategory_slug_name' => '授乳服', 'sort_no' => 174],
            ['id' => '175', 'category_id' => '1', 'subCategory_id' => '18', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 175],
            // レディース/その他
            ['id' => '176', 'category_id' => '1', 'subCategory_id' => '19', 'subSubCategory_name' => 'コスプレ', 'subSubCategory_slug_name' => 'コスプレ', 'sort_no' => 176],
            ['id' => '177', 'category_id' => '1', 'subCategory_id' => '19', 'subSubCategory_name' => '下着', 'subSubCategory_slug_name' => '下着', 'sort_no' => 177],
            ['id' => '178', 'category_id' => '1', 'subCategory_id' => '19', 'subSubCategory_name' => 'その他', 'subSubCategory_slug_name' => 'その他', 'sort_no' => 178],
        ];
        DB::table('sub_sub_categories')->insert($subSubCategories);
    }
}
