version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          key: composer-v2-{{ checksum "./server/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./server/
      - save_cache:
          key: composer-v2-{{ checksum "./server/composer.lock" }}
          paths: ./server/vendor
      - run:
          name: npm ci
          command: |
            if [ ! -d ./server/node_modules ]; then
              cd server/; npm ci
            fi
      - run: cd server/; npm run dev
      - run:
          name: php test
          command: php ./server/vendor/bin/phpunit --configuration=./server/phpunit.xml
